spring:
  profiles:
    active: local

  datasource:
    url:
    username:
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
    dbcp2:
      max-total: 25
      max-idle: 10
      min-idle: 5
      validation-query: SELECT 1 from dual
      validation-query-timeout: 1
      pool-prepared-statements: true

  http:
    encoding:
      charset: UTF-8

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        id:
          new_generator_mappings: false
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  servlet:
    context-path: /uaa
    session:
      timeout: 30m