spring:
  profiles:
    active: local
  datasource:
    url:  jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:

server:
  port: 9999
